import type { ToolSlug } from "@/lib/tools";

export const guideCategories = [
  { name: "Tax & Salary", slug: "tax-salary", description: "Current tax rules, salary examples and filing concepts explained in plain language." },
  { name: "Business", slug: "business", description: "Practical profit, pricing and COD decision guides for online sellers." },
  { name: "Bills", slug: "bills", description: "Understand the inputs, charges and limitations behind bill estimates." },
  { name: "Property", slug: "property", description: "Clear land-measurement references for Pakistan’s commonly used standards." },
  { name: "Personal Finance", slug: "personal-finance", description: "Everyday calculations explained with formulas, examples and careful assumptions." },
] as const;

export type GuideCategory = (typeof guideCategories)[number]["name"];
type Source = { organization: string; title: string; url?: string; note?: string };
type Section = { heading: string; paragraphs: string[]; bullets?: string[]; formula?: string };
type DataTable = { title: string; caption: string; columns: string[]; rows: string[][] };
type Visual = { title: string; caption: string; values: { label: string; value: number; display: string }[] };

export type Guide = {
  slug: string; category: GuideCategory; title: string; description: string; directAnswer: string;
  period: string; verified: string; freshness: "Evergreen" | "Review required";
  calculatorSlug: ToolSlug; calculatorLabel: string; featured?: boolean;
  takeaways: string[]; sections: Section[]; table?: DataTable; visual?: Visual;
  faqs: { question: string; answer: string }[]; sources: Source[];
};

const financeAct = "https://download1.fbr.gov.pk/Docs/20266291261044366FinanceAct2026.pdf";
const atl = "https://www.fbr.gov.pk/categ/active-taxpayer-list-income-tax/51147/30859/71168";
const nepraTariffs = "https://www.nepra.org.pk/tariff/Tariff.php";

export const guides: Guide[] = [
  {
    slug: "pakistan-salary-tax-slabs-2026-27", category: "Tax & Salary", featured: true,
    title: "Pakistan Salary Tax Slabs 2026–27", description: "A source-backed reference table for Pakistan’s salaried-person tax slabs for 2026–27, with marginal and effective rate examples.",
    directAnswer: "For 2026–27, salary tax is calculated on annual taxable salary using progressive slabs. Only the income inside each higher band is charged at that band’s marginal rate; the whole salary is not taxed at the highest rate reached.",
    period: "Tax Year 2026–27 · 1 July 2026 to 30 June 2027", verified: "10 September 2026", freshness: "Review required",
    calculatorSlug: "salary-tax-calculator-pakistan", calculatorLabel: "Calculate your salary tax",
    takeaways: ["Annual taxable salary determines the slab.", "The top rate reached is the marginal rate, not the effective rate.", "Monthly tax is an annual estimate divided by 12.", "Credits, exemptions and employer adjustments are outside the basic slab model."],
    sections: [
      { heading: "How the progressive slabs work", paragraphs: ["Start with annual taxable salary. Find the row containing that amount, take the fixed tax shown for that row, then add the marginal percentage of income above the row’s floor.", "Moving into a higher slab does not cause all earlier income to be taxed again at the higher rate."], formula: "Annual tax = fixed slab tax + (annual income − slab floor) × marginal rate" },
      { heading: "Marginal rate vs effective rate", paragraphs: ["The marginal rate applies to the next rupee inside the current band. The effective rate is total annual tax divided by annual income. It is normally lower because earlier portions of income are taxed at lower rates."], formula: "Effective rate = annual tax ÷ annual taxable salary × 100" },
      { heading: "Important scope", paragraphs: ["This reference explains the standard salaried-person slab calculation used by Seedha Hisab. It does not calculate tax credits, special exemptions, multiple income heads, arrears or a formal FBR assessment."] },
    ],
    table: { title: "Salaried-person slab reference", caption: "Recreated as accessible HTML from the Finance Act 2026 schedule used by this calculator.", columns: ["Annual taxable salary", "Fixed tax", "Rate above floor"], rows: [["Up to Rs 600,000","Rs 0","0%"],["Rs 600,001–1,200,000","Rs 0","1% above Rs 600,000"],["Rs 1,200,001–2,200,000","Rs 6,000","11% above Rs 1,200,000"],["Rs 2,200,001–3,200,000","Rs 116,000","20% above Rs 2,200,000"],["Rs 3,200,001–4,100,000","Rs 316,000","25% above Rs 3,200,000"],["Rs 4,100,001–5,600,000","Rs 541,000","29% above Rs 4,100,000"],["Rs 5,600,001–7,000,000","Rs 976,000","32% above Rs 5,600,000"],["Above Rs 7,000,000","Rs 1,424,000","35% above Rs 7,000,000"]] },
    visual: { title: "Annual salary vs estimated annual tax", caption: "Selected points calculated from the slab table; scale is relative to the largest tax value shown.", values: [{label:"Rs 1.2m salary",value:6000,display:"Rs 6,000"},{label:"Rs 2.4m salary",value:156000,display:"Rs 156,000"},{label:"Rs 3.6m salary",value:416000,display:"Rs 416,000"},{label:"Rs 5m salary",value:802000,display:"Rs 802,000"},{label:"Rs 7m salary",value:1424000,display:"Rs 1,424,000"}] },
    faqs: [{question:"Is monthly salary taxed separately?",answer:"Payroll may deduct monthly, but the slab estimate starts by annualising taxable salary and then dividing the annual result across the year."},{question:"Does entering a 20% slab mean all income is taxed at 20%?",answer:"No. The fixed amount captures lower bands and 20% applies only to income above that slab’s floor."}],
    sources: [{organization:"Federal Board of Revenue (FBR)",title:"Finance Act 2026 — First Schedule, Part I, Division I",url:financeAct,note:"Primary legal source used for the displayed slab model."}],
  },
  {
    slug: "how-to-calculate-salary-tax-pakistan", category: "Tax & Salary", featured: true,
    title: "How to Calculate Salary Tax in Pakistan", description: "A step-by-step salary-tax calculation with worked examples for Rs 100,000, Rs 200,000 and Rs 300,000 monthly salaries.",
    directAnswer: "Annualise the taxable monthly salary, select the applicable 2026–27 slab, add the slab’s fixed amount to the marginal tax above its floor, and divide the annual result by 12 for a monthly estimate.",
    period: "Tax Year 2026–27", verified: "10 September 2026", freshness: "Review required", calculatorSlug: "salary-tax-calculator-pakistan", calculatorLabel: "Calculate your exact salary tax",
    takeaways: ["Use annual taxable salary, not one month in isolation.", "Apply the fixed amount and only the excess above the slab floor.", "The calculator is an estimate before credits or payroll-specific adjustments."],
    sections: [
      {heading:"Four calculation steps",paragraphs:["Multiply monthly taxable salary by 12. Locate the annual amount in the slab table. Apply the fixed amount plus the rate on income above the floor. Divide annual tax by 12 to estimate a monthly deduction."],formula:"Monthly estimate = [fixed tax + (annual salary − slab floor) × rate] ÷ 12"},
      {heading:"Example: Rs 100,000 per month",paragraphs:["Annual salary is Rs 1,200,000. The estimate is 1% of Rs 600,000 above the tax-free floor, giving Rs 6,000 annually or Rs 500 monthly."]},
      {heading:"Example: Rs 200,000 per month",paragraphs:["Annual salary is Rs 2,400,000. Add Rs 116,000 to 20% of Rs 200,000 above the Rs 2,200,000 floor. The estimate is Rs 156,000 annually or Rs 13,000 monthly."]},
      {heading:"Example: Rs 300,000 per month",paragraphs:["Annual salary is Rs 3,600,000. Add Rs 316,000 to 25% of Rs 400,000. The estimate is Rs 416,000 annually or about Rs 34,667 monthly."]},
    ],
    table:{title:"Worked salary examples",caption:"Basic slab estimates before credits, exemptions or other payroll adjustments.",columns:["Monthly salary","Annual salary","Annual tax","Monthly tax"],rows:[["Rs 100,000","Rs 1,200,000","Rs 6,000","Rs 500"],["Rs 200,000","Rs 2,400,000","Rs 156,000","Rs 13,000"],["Rs 300,000","Rs 3,600,000","Rs 416,000","Rs 34,667"]]},
    faqs:[{question:"Why can payroll tax differ?",answer:"Bonuses, taxable benefits, prior deductions, credits, salary changes and employer payroll adjustments can change the amount withheld."}],
    sources:[{organization:"Federal Board of Revenue (FBR)",title:"Finance Act 2026 — salaried-person schedule",url:financeAct}],
  },
  {
    slug:"filer-vs-non-filer-pakistan",category:"Tax & Salary",title:"Filer vs Non-Filer in Pakistan: What Changes?",description:"Understand Active Taxpayer List status, why some withholding treatments differ, and how to compare a transaction carefully.",
    directAnswer:"In everyday usage, ‘filer’ generally refers to a person appearing on the Federal Board of Revenue’s Active Taxpayer List (ATL). Some transactions can carry different advance withholding treatment depending on ATL or other statutory status, but the exact rate depends on the transaction, date and applicable law.",
    period:"Tax Year 2026–27 concepts",verified:"10 September 2026",freshness:"Review required",calculatorSlug:"filer-vs-non-filer-calculator",calculatorLabel:"Compare a property transaction",
    takeaways:["ATL status is a specific FBR status, not just having an NTN.","Rates depend on the transaction and applicable date.","Advance withholding is not automatically the final tax liability.","Verify current status and the legal schedule before acting."],
    sections:[{heading:"What ATL status means",paragraphs:["FBR maintains the Active Taxpayer List. Its official guidance explains inclusion, late filing and the surcharge route for placement after the filing due date."],bullets:["Confirm status through FBR’s official ATL service.","Do not assume an old screenshot or previous year’s status is current."]},{heading:"Why transaction results differ",paragraphs:["The Income Tax Ordinance and schedules can prescribe different withholding treatments for property purchases, property sales and other transactions. A calculator comparison is useful for planning, but it is not a substitute for checking the exact section and current status."],formula:"Estimated withholding = statutory valuation basis × applicable transaction rate"},{heading:"Important limitation",paragraphs:["This guide does not label every person simply as ‘filer’ or ‘non-filer’ for every legal purpose. Late-filer or other statutory categories may matter. Confirm the live rule with FBR or a qualified adviser for a real transaction."]}],
    table:{title:"Comparison checklist",caption:"Use the same facts on both sides before comparing an estimate.",columns:["Question","Why it matters"],rows:[["Purchase or sale?","Different statutory sections may apply."],["ATL status on transaction date?","Status can affect applicable treatment."],["Valuation basis?","Withholding may use a prescribed value or consideration."],["Advance or final tax?","Withholding does not by itself settle every liability."]]},
    faqs:[{question:"Is having an NTN the same as being on the ATL?",answer:"Not necessarily. ATL inclusion depends on the relevant return and FBR’s current rules; check the official status service."}],
    sources:[{organization:"Federal Board of Revenue (FBR)",title:"Active Taxpayer List guidance",url:atl},{organization:"Federal Board of Revenue (FBR)",title:"Finance Act 2026 — relevant withholding provisions",url:financeAct}],
  },
  {
    slug:"freelancer-tax-pakistan-guide",category:"Tax & Salary",title:"Freelancer Tax in Pakistan — Practical Guide",description:"A careful explanation of the receipt-based estimate used for qualifying service exports, PSEB status and ATL assumptions.",
    directAnswer:"A freelancer’s tax treatment depends on the nature and source of income, registration and status, banking channel, documentation and current law. Seedha Hisab’s calculator models withholding on qualifying service-export receipts; it does not determine every freelancer’s final income-tax liability.",
    period:"FY 2026–27 model",verified:"10 September 2026",freshness:"Review required",calculatorSlug:"freelancer-tax-calculator-pakistan",calculatorLabel:"Estimate freelancer withholding",
    takeaways:["Confirm that receipts qualify as service-export proceeds.","PSEB registration and ATL status must be current where selected.","Use gross eligible receipts for a receipt-based estimate.","Keep invoices, contracts and banking evidence."],
    sections:[{heading:"What the calculator estimates",paragraphs:["The current model applies a selected Section 154A-style withholding rate to eligible gross export receipts. It separates the PSEB-registered IT/ITeS selection from other qualifying service exports and applies the calculator’s ATL assumption."],formula:"Estimated withholding = eligible gross export receipts × selected rate"},{heading:"Documentation checklist",paragraphs:["Good records help establish what the payment was for and how it arrived."],bullets:["Client contract or scope","Invoice and payment advice","Bank credit advice or remittance evidence","Current registration/status evidence where relied upon","Expense and return records for final tax work"]},{heading:"Common mistakes",paragraphs:["Do not mix local sales with export receipts, assume every foreign payment automatically qualifies, or treat withholding as a complete assessment of final liability."]}],
    table:{title:"Calculator rate selections",caption:"These are the assumptions used by the current estimator and require verification for the user’s facts.",columns:["Selection","ATL model rate","Off-ATL model rate"],rows:[["PSEB-registered IT/ITeS","0.25%","0.50%"],["Other qualifying service export","1.00%","2.00%"]]},
    faqs:[{question:"Is tax deducted by the bank always my final tax?",answer:"Not in every situation. Final treatment depends on the applicable law and your complete facts; the calculator only models the selected withholding basis."}],sources:[{organization:"Federal Board of Revenue (FBR)",title:"Finance Act 2026 and Section 154A framework",url:financeAct}],
  },
  {
    slug:"profit-margin-vs-markup",category:"Business",featured:true,title:"Profit Margin vs Markup — What’s the Difference?",description:"Learn profit, margin and markup with a Rs 45,000 cost and Rs 60,000 selling-price example.",
    directAnswer:"Profit is selling price minus cost. Margin expresses profit as a percentage of selling price, while markup expresses the same profit as a percentage of cost. They are not interchangeable.",period:"Evergreen",verified:"11 September 2026",freshness:"Evergreen",calculatorSlug:"profit-margin-calculator",calculatorLabel:"Calculate margin and markup",
    takeaways:["Profit is a rupee amount.","Margin divides profit by selling price.","Markup divides profit by cost.","A 25% margin is not a 25% markup."],
    sections:[{heading:"Worked example",paragraphs:["If a product costs Rs 45,000 and sells for Rs 60,000, profit is Rs 15,000. Margin is 15,000 ÷ 60,000 = 25%. Markup is 15,000 ÷ 45,000 = 33.33%."],formula:"Profit = selling price − cost · Margin = profit ÷ selling price · Markup = profit ÷ cost"},{heading:"Which percentage should you use?",paragraphs:["Use margin when asking what share of revenue remains as profit. Use markup when adding a percentage to cost to set a price. Always state which one you mean in pricing discussions."]}],
    table:{title:"One profit, two percentages",caption:"Both percentages describe the same Rs 15,000 profit from different bases.",columns:["Measure","Calculation","Result"],rows:[["Profit","Rs 60,000 − Rs 45,000","Rs 15,000"],["Margin","Rs 15,000 ÷ Rs 60,000","25%"],["Markup","Rs 15,000 ÷ Rs 45,000","33.33%"]]},
    visual:{title:"Where the percentage starts",caption:"Margin uses sales as the 100% base; markup uses cost.",values:[{label:"Profit margin",value:25,display:"25% of sales"},{label:"Markup",value:33.33,display:"33.33% of cost"}]},
    faqs:[{question:"What selling price gives a 25% margin on Rs 45,000 cost?",answer:"Rs 60,000, because Rs 45,000 ÷ (1 − 0.25) = Rs 60,000."}],sources:[{organization:"Seedha Hisab",title:"Standard arithmetic definitions and worked calculation",note:"Recalculate instantly with the linked tool."}],
  },
  {
    slug:"cod-returns-ecommerce-profit-pakistan",category:"Business",featured:true,title:"How COD Returns Affect E-commerce Profit in Pakistan",description:"An original 100-order comparison showing how delivery rate, RTO courier charges and fixed acquisition costs change profit.",
    directAnswer:"COD returns reduce profit in two directions: fewer orders generate revenue, while failed deliveries can still consume packaging, advertising and return-courier costs. Delivery rate therefore changes profit more sharply than a simple lost-sale count suggests.",period:"Evergreen scenario model",verified:"11 September 2026",freshness:"Evergreen",calculatorSlug:"cod-profit-calculator",calculatorLabel:"Model your COD profit",
    takeaways:["Separate dispatched, delivered and returned orders.","Charge revenue only to delivered orders.","Include RTO courier cost and packaging on failed deliveries.","Compare scenarios using your own store data, not invented industry averages."],
    sections:[{heading:"The 100-order model",paragraphs:["The comparison below holds price and costs constant and changes only delivery rate. Assumptions: Rs 3,000 price, Rs 1,200 product cost per delivered order, Rs 200 outward courier per delivered order, Rs 200 RTO courier per return, Rs 100 packaging per dispatched order, 2% COD fee, Rs 50,000 ads and Rs 10,000 overhead."],formula:"Net profit = delivered sales − product − courier − RTO − packaging − COD fee − ads − overhead"},{heading:"Why the profit drop is larger than it looks",paragraphs:["Moving from 90% to 75% delivery removes revenue from 15 orders. It also leaves acquisition and dispatch spending spread over fewer successful deliveries and adds more return-courier cost."]},{heading:"Use your own evidence",paragraphs:["Export order, delivery and return data from the same date range. Keep courier and ad-spend periods aligned. Do not rely on a general market return-rate claim when your own courier reconciliation is available."]}],
    table:{title:"90% vs 75% delivery",caption:"Original Seedha Hisab scenario; figures are illustrative, not an industry benchmark.",columns:["Metric","90% delivery","75% delivery","Change"],rows:[["Delivered / returned","90 / 10","75 / 25","−15 delivered"],["Sales","Rs 270,000","Rs 225,000","−Rs 45,000"],["Total modeled cost","Rs 203,400","Rs 184,500","−Rs 18,900"],["Net profit","Rs 66,600","Rs 40,500","−Rs 26,100"],["Net margin","24.67%","18.00%","−6.67 points"]]},
    visual:{title:"Profit by delivery scenario",caption:"Same 100 dispatched orders and cost assumptions; only delivery rate changes.",values:[{label:"90% delivered",value:66600,display:"Rs 66,600"},{label:"75% delivered",value:40500,display:"Rs 40,500"}]},
    faqs:[{question:"Should product cost be charged to returned orders?",answer:"The default model charges product cost to delivered orders because returned stock may be recoverable. Add damage or non-recoverable loss to overhead when relevant."}],sources:[{organization:"Seedha Hisab",title:"Original COD scenario methodology",note:"No external industry-average return rate is assumed."}],
  },
  {
    slug:"electricity-bill-estimation-pakistan",category:"Bills",title:"How Electricity Bills Are Estimated in Pakistan",description:"Understand energy charges, fixed charges, adjustments, taxes and why an estimate may differ from the issued bill.",
    directAnswer:"An electricity estimate starts with units and the tariff applicable to the connection, then adds relevant fixed charges, fuel or other adjustments and taxes. Because tariff category, billing period and provider-specific items vary, a manual-rate calculator should be treated as an estimate—not a duplicate of the issued bill.",period:"User-selected current tariff",verified:"10 September 2026",freshness:"Review required",calculatorSlug:"electricity-bill-calculator-pakistan",calculatorLabel:"Estimate your electricity bill",
    takeaways:["Read units and tariff category from the current bill.","Do not use a stale nationwide average rate.","Add fixed charges and adjustments separately.","Arrears, meter rent and provider-specific items can create differences."],
    sections:[{heading:"Core bill components",paragraphs:["The energy charge is based on units and the applicable tariff structure. Other bill lines can include fixed charges, fuel-cost adjustments, taxes, arrears and provider-specific adjustments."],formula:"Estimate = energy charge + fixed charges + adjustments + entered taxes"},{heading:"Protected and unprotected treatment",paragraphs:["Where a tariff or consumer classification distinguishes protected and unprotected consumers, use the status shown by the relevant bill and current tariff material. Do not infer status from units alone without checking the applicable rules."]},{heading:"Why the issued bill may differ",paragraphs:["Slab treatment, billing days, prior adjustments, taxes on different bases, arrears, meter changes and utility-specific line items can all affect the final issued amount."]}],
    table:{title:"Bill-input checklist",caption:"Use the latest bill and current tariff notice for these inputs.",columns:["Input","Where to check","Common error"],rows:[["Units","Meter reading / bill","Using an estimate from a different month"],["Tariff/category","Connection details","Using a residential rate for another category"],["Fixed charges","Tariff/bill line","Leaving them inside the per-unit rate"],["FCA/adjustments","Current bill notice","Assuming they never change"],["Taxes/arrears","Bill lines","Applying one percentage to every item"]]},
    faqs:[{question:"Can an online calculator reproduce the exact bill?",answer:"Not reliably without every current tariff rule and provider-specific adjustment. Seedha Hisab intentionally labels this tool an estimator."}],sources:[{organization:"National Electric Power Regulatory Authority (NEPRA)",title:"Official tariff determinations and schedules",url:nepraTariffs,note:"Select the relevant utility and current determination."}],
  },
  {
    slug:"marla-to-square-feet-pakistan-standards",category:"Property",title:"Marla to Square Feet in Pakistan — Why Standards Differ",description:"Compare 225, 250 and 272.25 square-foot marla conventions with accessible conversion tables.",
    directAnswer:"Pakistan does not use one universal marla size in every property context. Common calculation conventions include 225, 250 and 272.25 square feet per marla. The correct choice is the one used by the relevant deed, authority, housing society or transaction document.",period:"Evergreen · local convention must be confirmed",verified:"11 September 2026",freshness:"Evergreen",calculatorSlug:"marla-to-square-feet-calculator",calculatorLabel:"Convert land area",
    takeaways:["Select the standard before converting.","One kanal is commonly calculated as 20 marla within the selected convention.","The same ‘5 marla’ label can represent different square-foot areas.","Use property documents as the deciding reference."],
    sections:[{heading:"Why one answer can be misleading",paragraphs:["A calculator that silently assumes one marla size can produce a precise-looking but contextually wrong result. Seedha Hisab requires the user to choose the convention."],formula:"Square feet = number of marla × selected square feet per marla"},{heading:"How to choose",paragraphs:["Check the sale deed, allotment letter, approved plan, development-authority record or housing-society documentation. If documents conflict, obtain clarification before pricing or construction decisions."]},{heading:"Other useful conversions",paragraphs:["One square yard (gaz) equals 9 square feet. One square metre is approximately 10.7639 square feet. Keep rounding until the final display to avoid compounding error."]}],
    table:{title:"Common marla convention comparison",caption:"The table shows why the selected standard materially changes the result.",columns:["Land label","225 sq ft/marla","250 sq ft/marla","272.25 sq ft/marla"],rows:[["1 marla","225 sq ft","250 sq ft","272.25 sq ft"],["5 marla","1,125 sq ft","1,250 sq ft","1,361.25 sq ft"],["10 marla","2,250 sq ft","2,500 sq ft","2,722.50 sq ft"],["1 kanal (20 marla)","4,500 sq ft","5,000 sq ft","5,445 sq ft"]]},
    visual:{title:"Five marla under three conventions",caption:"All bars say ‘5 marla’, but the square-foot result depends on the selected convention.",values:[{label:"225 standard",value:1125,display:"1,125 sq ft"},{label:"250 standard",value:1250,display:"1,250 sq ft"},{label:"272.25 standard",value:1361.25,display:"1,361.25 sq ft"}]},
    faqs:[{question:"Which marla standard is legally correct?",answer:"The answer depends on the relevant document and authority. This guide does not assign one convention to every area or society."}],sources:[{organization:"Seedha Hisab",title:"Multiple-standard conversion methodology",note:"The tool keeps the convention user-selected and makes it visible in the result."}],
  },
  {
    slug:"how-zakat-calculator-works",category:"Personal Finance",title:"How a Zakat Calculator Works",description:"Understand the 2.5% net-assets method, user-selected nisab and the difference between a calculator method and a religious ruling.",
    directAnswer:"A basic Zakat calculator totals assets the user considers zakatable, subtracts eligible short-term liabilities, compares the net amount with the user’s chosen nisab, and applies 2.5% when the calculator’s conditions are met.",period:"Current user-entered values",verified:"11 September 2026",freshness:"Review required",calculatorSlug:"zakat-calculator-pakistan",calculatorLabel:"Calculate your Zakat estimate",
    takeaways:["Use a current nisab value from a trusted authority you follow.","Include only assets and liabilities relevant to your chosen method.","The common calculator rate is 2.5% when conditions are met.","A calculator is not a fatwa."],
    sections:[{heading:"The calculator method",paragraphs:["Enter eligible cash, precious metals, investments, receivables and business inventory according to the method you follow. Subtract eligible liabilities, then compare net assets with nisab."],formula:"Estimated Zakat = (eligible assets − eligible liabilities) × 2.5%"},{heading:"Worked example",paragraphs:["If net eligible assets are Rs 1,500,000 and that amount is above the nisab selected by the user, the 2.5% estimate is Rs 37,500."]},{heading:"Methodology vs religious ruling",paragraphs:["Questions about hawl, jewellery, debts, mixed assets, business inventory or a particular school of thought may require qualified religious guidance. Seedha Hisab makes the mathematical method visible but does not issue a ruling."]}],
    table:{title:"Asset checklist",caption:"Classification may differ by the religious guidance a user follows.",columns:["Input group","Calculator treatment"],rows:[["Cash and bank balances","Add when considered eligible"],["Gold and silver","Enter the current eligible value"],["Business inventory","Enter qualifying inventory value"],["Receivables","Include according to the method followed"],["Eligible liabilities","Subtract before the nisab comparison"]]},
    faqs:[{question:"Does the calculator choose nisab for me?",answer:"No. It lets the user enter a current nisab value from the trusted authority or methodology they follow."}],sources:[{organization:"Seedha Hisab",title:"User-selected nisab and standard 2.5% calculator method",note:"Seek qualified religious guidance for classification or ruling questions."}],
  },
  {
    slug:"percentage-discount-calculation",category:"Personal Finance",title:"How to Calculate a Percentage Discount",description:"Calculate discount amount and final price, including a Rs 45,000 price with 25% off and sequential discounts.",
    directAnswer:"Multiply the original price by the discount percentage to find the amount saved, then subtract that amount from the original price. A Rs 45,000 item at 25% off saves Rs 11,250 and costs Rs 33,750.",period:"Evergreen",verified:"11 September 2026",freshness:"Evergreen",calculatorSlug:"discount-calculator",calculatorLabel:"Calculate a discount",
    takeaways:["Convert the percentage to a decimal.","Discount amount and final price are different results.","Two discounts are usually sequential, not simply added.","Check whether taxes or delivery are calculated before or after discount."],
    sections:[{heading:"One discount",paragraphs:["For 25%, use 0.25. Multiply Rs 45,000 by 0.25 to get Rs 11,250 saved, then subtract it from Rs 45,000."],formula:"Discount amount = original price × discount % · Final price = original price − discount amount"},{heading:"Sequential discounts",paragraphs:["A 20% discount followed by 10% does not normally equal 30% off. The second 10% applies to the already reduced price, producing an effective discount of 28%."],formula:"Final = original × (1 − first discount) × (1 − second discount)"}],
    table:{title:"Rs 45,000 at 25% off",caption:"A transparent breakdown of the example.",columns:["Step","Calculation","Result"],rows:[["Discount amount","Rs 45,000 × 0.25","Rs 11,250"],["Final price","Rs 45,000 − Rs 11,250","Rs 33,750"],["Amount paid","Rs 45,000 × 0.75","Rs 33,750"]]},
    faqs:[{question:"Can I add two discount percentages?",answer:"Not when the second is applied after the first. Multiply the remaining-price factors to find the effective combined discount."}],sources:[{organization:"Seedha Hisab",title:"Standard percentage arithmetic",note:"The linked tool supports one or two sequential discounts."}],
  },
  {
    slug:"net-salary-vs-gross-salary-pakistan",category:"Tax & Salary",featured:false,
    title:"Net Salary vs Gross Salary in Pakistan",description:"Understand the difference between gross and net (take-home) salary in Pakistan, with a worked 2026–27 example and the deductions that commonly apply.",
    directAnswer:"Gross salary is the full amount stated in an offer letter or contract before any deduction. Net salary — also called take-home pay — is what actually reaches the bank account after income tax and any other agreed deductions such as provident fund are subtracted.",
    period:"Tax Year 2026–27",verified:"18 September 2026",freshness:"Review required",calculatorSlug:"net-salary-calculator-pakistan",calculatorLabel:"Calculate your take-home salary",
    takeaways:["Gross salary is the contract figure; net salary is what is actually received.","Income tax is calculated on annualised taxable salary, then divided across 12 months.","Provident fund, loan recovery or other agreed deductions reduce net salary further.","A payslip's net figure can differ slightly from a basic calculator due to employer-specific adjustments."],
    sections:[
      {heading:"What separates gross from net",paragraphs:["Gross monthly salary is multiplied by 12 to estimate annual taxable salary, which is matched against the 2026–27 slab table to find annual tax. That tax is divided by 12 for a monthly estimate, then subtracted from gross salary along with any other deductions the employee enters."],formula:"Net monthly salary = gross monthly salary − (annual tax ÷ 12) − other monthly deductions"},
      {heading:"Worked example: Rs 250,000 monthly",paragraphs:["Annual salary is Rs 3,000,000. Using the 2026–27 slabs, annual tax is Rs 116,000 plus 20% of the Rs 800,000 above the Rs 2,200,000 floor, which is Rs 276,000 annual tax, or Rs 23,000 monthly. With no other deductions entered, take-home pay is Rs 250,000 − Rs 23,000 = Rs 227,000 per month."]},
      {heading:"Why a payslip can differ from the estimate",paragraphs:["Employers may apply provident fund contributions, benevolent fund, EOBI, loan instalments, health-insurance premiums or tax credits that a basic calculator does not know about. Bonuses or arrears paid in a single month can also push that month's withholding higher than a flat monthly estimate suggests."]},
    ],
    table:{title:"Gross vs estimated net at three salary levels",caption:"2026–27 slabs, no additional deductions entered.",columns:["Gross monthly salary","Annual salary","Annual tax","Estimated net monthly"],rows:[["Rs 150,000","Rs 1,800,000","Rs 72,000","Rs 144,000"],["Rs 250,000","Rs 3,000,000","Rs 276,000","Rs 227,000"],["Rs 400,000","Rs 4,800,000","Rs 744,000","Rs 338,000"]]},
    faqs:[
      {question:"Is net salary the same as take-home pay?",answer:"Yes, the terms are used interchangeably — both mean the amount actually paid out after tax and other deductions."},
      {question:"Does provident fund reduce taxable salary?",answer:"Treatment depends on the specific fund type and employer scheme; enter any such deduction manually since the base calculator does not assume one."},
      {question:"Why is my actual payslip different from this estimate?",answer:"Bonuses, arrears, tax credits, loan recoveries and employer-specific benefits can all change the withheld amount in a way a basic slab calculator cannot see."},
    ],
    sources:[{organization:"Federal Board of Revenue (FBR)",title:"Finance Act 2026 — First Schedule, Part I, Division I",url:financeAct,note:"Same salary-slab source used by the salary tax calculator."}],
  },
  {
    slug:"daraz-fbm-vs-fbd-which-is-more-profitable",category:"Business",featured:false,
    title:"Daraz FBM vs FBD: Which Fulfilment Model Is More Profitable?",description:"Compare Fulfilled-by-Merchant and Fulfilled-by-Daraz profit on the same product, with a worked Rs 2,000 fashion-item example and the fee categories that separate the two models.",
    directAnswer:"Neither model is universally more profitable — FBM avoids Daraz's flat Pick & Pack and storage fees but pays for shipping and handling by weight and zone, while FBD replaces those with fixed per-order and monthly charges. Which one nets more depends on the product's weight, how fast it sells and your own packaging cost, so compare both for each product rather than picking one model for the whole store.",
    period:"2026 fee estimates",verified:"18 September 2026",freshness:"Review required",calculatorSlug:"daraz-profit-calculator",calculatorLabel:"Compare FBM vs FBD for your product",
    takeaways:["Commission, payment fee and VAT are identical for FBM and FBD on the same product.","FBM shipping and handling scale with weight and shipping zone.","FBD replaces shipping and handling with a flat Pick & Pack fee plus optional storage.","Light, fast-moving items often net more under FBD; heavy or slow-moving stock can cost more in FBD storage than it saves in shipping."],
    sections:[
      {heading:"What's shared between FBM and FBD",paragraphs:["Both models deduct the same category-based commission, the same 2.25% payment fee, and VAT calculated on those Daraz fees at the seller's provincial rate (15% in Sindh, KPK and Balochistan; 16% in Punjab). None of these three change based on fulfilment model — only the fulfilment costs differ."],formula:"Shared deductions = commission + payment fee + VAT on (commission + payment fee + fulfilment fee)"},
      {heading:"Where FBM and FBD diverge",paragraphs:["FBM (Fulfilled by Merchant) charges a shipping fee that rises with parcel weight and the shipping zone, plus a handling fee banded by selling price for drop-off or a separate weight-banded fee if a rider picks up the parcel. Items at or above 8kg carry an additional bulky-item surcharge.","FBD (Fulfilled by Daraz) replaces both of those with a flat Pick & Pack fee per delivered order, plus an optional monthly storage charge if inventory sits unsold for roughly 30 days or longer."],bullets:["FBM: shipping fee (by zone and weight) + handling fee (by price or weight)","FBD: Pick & Pack fee (flat) + storage fee (only if aged)"]},
      {heading:"Worked example: Rs 2,000 fashion item",paragraphs:["A Rs 2,000 item costing Rs 900 to source, sold to a buyer in Sindh, weighing 500g and shipped door-to-door in Zone 1: under FBM with drop-off handling, the estimate nets about Rs 494 profit (24.7% margin). Under FBD with a Rs 60 Pick & Pack fee and no storage cost, the estimate nets about Rs 565 profit (28.3% margin) — FBD comes out about Rs 71 ahead for this specific light, fast-selling item."]},
      {heading:"When FBM can win instead",paragraphs:["Heavier items, slow-moving stock that accrues FBD storage charges over several months, or sellers who already have efficient in-house packing and a low-cost courier account can find FBM competitive or cheaper. There is no single right answer — the calculator is built to compare both for the exact product in front of you."]},
    ],
    table:{title:"FBM vs FBD deduction categories",caption:"Commission, payment fee and VAT are identical; only the fulfilment line differs.",columns:["Deduction","FBM","FBD"],rows:[["Commission","Category rate","Category rate (same)"],["Payment fee","2.25%","2.25% (same)"],["Fulfilment cost","Shipping + handling (by weight/zone)","Pick & Pack (flat) + storage (if aged)"],["VAT base","Commission + payment + handling","Commission + payment + Pick & Pack"]]},
    faqs:[
      {question:"Do FBM and FBD pay different commission on the same product?",answer:"No. Category commission, the 2.25% payment fee and provincial VAT are the same regardless of fulfilment model — only the fulfilment-cost line item differs."},
      {question:"Is FBD always cheaper because it has fewer line items?",answer:"Not necessarily. A single flat Pick & Pack fee can beat per-kilogram shipping for light items, but monthly storage on slow-moving or heavy stock can make FBD more expensive over time."},
      {question:"What counts as a bulky item?",answer:"Parcels at or above roughly 8kg are treated as bulky and carry an estimated shipping surcharge under FBM in this calculator's model."},
    ],
    sources:[{organization:"Seedha Hisab",title:"Publicly reported Daraz seller fee structure (2026)",note:"Category commission and fee bands are commonly reported estimates, not an official Daraz price list; not affiliated with or endorsed by Daraz. Confirm exact figures in your Daraz Seller Center."}],
  },
];

export function getGuide(slug: string) { return guides.find((guide) => guide.slug === slug); }
export function getGuideCategory(slug: string) { return guideCategories.find((category) => category.slug === slug); }
export function getGuidesByCategory(category: GuideCategory) { return guides.filter((guide) => guide.category === category); }
export function getGuidesByTool(slug: ToolSlug) { return guides.filter((guide) => guide.calculatorSlug === slug); }
