import type { ToolSlug } from "@/lib/tools";

type Detail = { answer:string; formula:string; example:string; assumptions:string[]; source:string; sourceUrl?:string; verified:string; period:string };
const fbr = "https://download1.fbr.gov.pk/Docs/20266291261044366FinanceAct2026.pdf";
const verified = "10 September 2026";

export const toolContent: Record<ToolSlug, Detail> = {
  "salary-tax-calculator-pakistan": { answer:"Estimate monthly and annual salary tax under Pakistan’s enacted 2026–27 salaried-person slabs.", formula:"Fixed slab tax + marginal rate × income above the slab floor.", example:"At Rs 200,000 monthly, annual income is Rs 2,400,000. Tax is Rs 116,000 plus 20% of income above Rs 2,200,000.", assumptions:["Entered salary is taxable salary.","Credits and employer-specific deductions are excluded.","Results are estimates, not an FBR assessment."], source:"FBR — Finance Act 2026, First Schedule", sourceUrl:fbr, verified, period:"Tax Year 2026–27" },
  "freelancer-tax-calculator-pakistan": { answer:"Estimate withholding on eligible service-export receipts, including the PSEB-registered IT/ITeS rate.", formula:"Eligible gross export receipts × applicable Section 154A rate.", example:"A PSEB-registered exporter on the ATL entering Rs 4,800,000 gets a 0.25% estimate of Rs 12,000.", assumptions:["Receipts qualify under Section 154A.","PSEB registration and ATL status are current.","Funds arrive through qualifying banking channels."], source:"Finance Act 2026; FBR Section 154A framework", sourceUrl:fbr, verified, period:"FY 2026–27" },
  "filer-vs-non-filer-calculator": { answer:"Compare estimated property transaction withholding when a person is on or off the ATL.", formula:"Value × section 236K purchase rate or consideration × section 236C sale rate.", example:"On a Rs 10,000,000 purchase, the base 236K estimate at 1.25% is Rs 125,000.", assumptions:["This is advance withholding, not final capital-gains tax.","The entered amount matches the statutory valuation basis.","Special exemptions are excluded."], source:"FBR — Finance Act 2026, sections 236C/236K and Tenth Schedule", sourceUrl:fbr, verified, period:"Tax Year 2026–27" },
  "cod-profit-calculator": { answer:"Model profit after delivery failures, RTO courier cost, packaging, COD fees, ads and overhead.", formula:"Delivered sales − all modeled delivered, failed-delivery and operating costs.", example:"100 orders at a 70% delivery rate models 70 delivered orders and 30 returns.", assumptions:["Product cost is charged to delivered orders.","Packaging applies to every dispatched order.","Courier fields follow the labels shown."], source:"Seedha Hisab business methodology", verified, period:"Evergreen model" },
  "daraz-profit-calculator": { answer:"Compare Fulfilled-by-Merchant (FBM) and Fulfilled-by-Daraz (FBD) profit on the same product side by side.", formula:"Selling price − commission − payment fee − VAT on fees − fulfilment costs (FBM: shipping + handling; FBD: pick & pack + storage) − penalties − product cost.", example:"A Rs 2,000 fashion item costing Rs 900 in Sindh nets about Rs 494 under FBM (500g, Zone 1, drop-off) versus about Rs 565 under FBD (Rs 60 pick & pack fee).", assumptions:["Category commission and provincial VAT are commonly reported ranges, not an official Daraz price list.","Drop-off handling fee is banded by selling price; pickup uses a separate weight-banded fee that replaces it entirely.","Items at or above 8kg are treated as bulky and carry an estimated shipping surcharge.","Voucher Max and Free Shipping Max are optional and only apply when toggled on.","Penalties (returns, quality issues) are entered manually and reduce profit for both models equally."], source:"Publicly reported Daraz seller fee structure (2026); not affiliated with or endorsed by Daraz", verified, period:"2026 fee estimates" },
  "profit-margin-calculator": { answer:"See profit, margin, markup and the selling price required for a target margin.", formula:"Margin = profit ÷ selling price. Markup = profit ÷ cost.", example:"Rs 1,000 cost and Rs 1,500 selling price gives Rs 500 profit, 33.33% margin and 50% markup.", assumptions:["Cost and price cover the same unit.","Taxes and fees are included if relevant."], source:"Standard arithmetic definitions", verified, period:"Evergreen" },
  "marla-to-square-feet-calculator": { answer:"Convert land area without pretending every Pakistani property uses the same marla.", formula:"Square feet = marla × selected standard; 1 kanal = 20 marla.", example:"Five marla is 1,125 sq ft at 225, but 1,361.25 sq ft at the traditional 272.25 standard.", assumptions:["The selected standard matches the deed or society record.","Gaz means square yard."], source:"Punjab measurement convention; user-selected local standard", verified, period:"Evergreen; standards vary" },
  "electricity-bill-calculator-pakistan": { answer:"Create an honest bill estimate using the tariff and adjustments that apply to your connection.", formula:"Units × tariff + fixed charges + adjustments + entered tax percentage.", example:"Enter the rate from your current tariff category instead of relying on a stale nationwide average.", assumptions:["The entered rate is current.","Arrears and provider-specific items may differ."], source:"Manual-rate methodology; provider/month verification required", verified, period:"User-selected tariff" },
  "zakat-calculator-pakistan": { answer:"Calculate 2.5% of net zakatable assets when they meet the nisab value you follow.", formula:"(Eligible assets − eligible liabilities) × 2.5%.", example:"Net eligible assets of Rs 1,500,000 produce Rs 37,500 when above nisab.", assumptions:["Relevant hawl conditions are met.","The user chooses a current nisab.","Religious treatment may differ."], source:"User-selected nisab; standard 2.5% method", verified, period:"Current entered values" },
  "net-salary-calculator-pakistan": { answer:"Estimate monthly take-home salary after 2026–27 tax and deductions you enter.", formula:"Gross monthly salary − estimated tax − other deductions.", example:"Monthly pay is annualised, the annual slab is applied, then tax is divided across 12 months.", assumptions:["Salary is consistent through the year.","Other deductions are entered manually."], source:"FBR — Finance Act 2026, First Schedule", sourceUrl:fbr, verified, period:"Tax Year 2026–27" },
  "discount-calculator": { answer:"Calculate the amount saved and final price after one or two sequential discounts.", formula:"Final = original × (1 − discount 1) × (1 − discount 2).", example:"Rs 45,000 at 25% off saves Rs 11,250 and gives Rs 33,750.", assumptions:["Discounts are percentages.","A second discount applies after the first."], source:"Standard arithmetic definition", verified, period:"Evergreen" }
};
